#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Richard J Gowers

# Short bio or description (displayed in the header)
description: Time traveller of the year 2055

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

js: /js
data: /data

# Includes an icon in the footer for each username you enter
footer-links:
  github: richardjgowers
  twitter: richardjgowers

# see https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed

url: http://richardjgowers.github.io

baseurl: ""
